export const REFERENCE_URL = {
    API: '/Reference/api',
    API_ORG_CATEGORIES: '/Reference/api/org-categories',
    API_DEPARTMENT_TYPES: '/Reference/api/department-types',
    API_DOCUMENT_LANGUAGES: '/Reference/api/document-languages',
    API_DOCUMENT_SUBJECTS: '/Reference/api/document-subjects',
    API_DOCUMENT_TYPES: '/Reference/api/document-types',
    API_CONTROL_TYPES: '/Reference/api/control-types',
    API_POSITIONS: '/Reference/api/positions',
    API_TAGS: '/Reference/api/tags',
    //
    API_COUNTRIES: '/Reference/api/countries',
    API_REGIONS: '/Reference/api/regions',
    API_DISTRICTS: '/Reference/api/districts',
    API_CITY_DISTRICTS: '/Reference/api/city-districts',
    API_LOCALITIES: '/Reference/api/localities',
    API_STREETS: '/Reference/api/streets',
    API_LOCALITY_TYPES: '/Reference/api/locality-types',
    API_REGION_TYPES: '/Reference/api/region-types',
    //
    API_TEXT_TEMPLATES: '/Reference/api/text-templates',
    API_NATIONALITIES: '/Reference/api/nationalities',
    API_DEMAND_TYPES: '/Reference/api/demand-types',
    API_ACTIVITY_TYPE_CATEGORIES: '/Reference/api/activity-type-categories',
    API_INDUSTRY_TYPES: '/Reference/api/industry-types',
    API_KUF: '/Reference/api/kuf',
    API_LAND_CLASSIFICATION: '/Reference/api/land-classifications',
    API_BUS_CLASSIFICATION: '/Reference/api/bus-classifications',
    API_MEETING_ROOMS: '/Reference/api/meeting-rooms',
    API_VEHICLES: '/Reference/api/vehicles',
    API_BUILDING_MATERIALS: '/Reference/api/building-materials',
    API_BUILDING_STATES: '/Reference/api/building-states',
    API_PROPERTY_CODES: '/Reference/api/property-codes',
    API_REAL_ESTATE_PURPOSES: '/Reference/api/realestate-purposes',
    API_REAL_ESTATE_OBJ_STATUSES: '/Reference/api/real-estate-obj-statuses',
    API_REQUEST_TYPES: '/Reference/api/request-types',
    API_RESPONSIBLE_TYPES: '/Reference/api/responsible-types',
    API_STRUCTURE_TYPES: '/Reference/api/structure-types',
    API_TASK_TYPES: '/Reference/api/task-types',
    API_WORK_TYPES: '/Reference/api/work-types',
    API_ROUTE_CLASSIFICATION: '/Reference/api/route-classifications',
    API_ROUTE_STATUS: '/Reference/api/route-statuses',
    API_ROAD_TYPES: '/Reference/api/road-types',
    API_REVENUE_CATEGORY: '/Reference/api/revenue-categories',
    API_EXPENDITURE_CATEGORY: '/Reference/api/expenditure-categories',
    API_ENG_INFRASTRUCT_OBJ_CLASSIFICATION: '/Reference/api/eng-infrastruct-obj-classifications',
    API_NATURE_CONSERVATION_OBJ_TYPE: '/Reference/api/nature-conservation-obj-types'
};
